# Generated by Django 3.2.6 on 2021-08-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_blog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
