# Generated by Django 3.2.6 on 2021-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_blog_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
